### ISSUE TITLE
userInfo fails on several points

### ISSUE THREAD

**Issue by fiddur** [agmoyano/OpenIDConnect#20]
I am trying to get this working, accessing it with passport-openidconnect.  But when it tries to access the userInfo endpoint, I had to fix several issues: (this is not a pull request, yet atleast, since I'm not sure the changes are correct)

From what I can see in [the OpenID Connect specification](http://openid.net/specs/openid-connect-core-1_0.html#UserInfoRequest), the request would look something like this:
```
GET /userinfo HTTP/1.1
Host: server.example.com
Authorization: Bearer SlAV32hkKG
```

1. In userInfo (line [1083](https://github.com/agmoyano/OpenIDConnect/blob/master/index.js#L1083)) self.use('user') make that request redirect to login.  I fixed that with `policies: {loggedIn: false}`.
2. Then, it tries to use `req.session.user` to lookup the user, but this backend request is made without cookies and thereby without session.  I added `'access'` to the use statement above, and fetched access, getting user from that instead.  I ended up with
```javascript
            function(req, res, next) {
                req.model.access.findOne({token: req.parsedParams.access_token})
                .exec(function(err, access) {
                    if(!err && access) {
                        req.model.user.findOne({id: access.user}, function(err, user) {
                            if(req.check.scopes.indexOf('profile') != -1) {
                                user.sub = req.session.sub||req.session.user;
                                delete user.id;
                                delete user.password;
                                delete user.openidProvider;
                                res.json(user);
                            } else {
                                res.json({email: user.email});
                            }
                        });
                    } else {
                        self.errorHandle(res, null, 'unauthorized_client', 'Access token is not valid.');
                    }
                });
            }
```

If this seems right, I could make a pull request.  I don't see how userInfo endpoint could have worked though…?

**Comment by agmoyano** [comment]
Yes, thank you! you're right, this shouldn't use cookies! 

PR please
