### ISSUE TITLE
Incorrect idtoken hash property name

### ISSUE THREAD

**Issue by xgfd** [agmoyano/OpenIDConnect#24]
[Line 639 of file index.js](https://github.com/agmoyano/OpenIDConnect/blob/master/index.js#L639), `resp.id_token.ht_hash` should be `resp.id_token.at_hash` according to the [spec](http://openid.net/specs/openid-connect-core-1_0.html#CodeIDToken)?

**Comment by agmoyano** [comment]
ups!, must have been a typo. I'll get to it asap (or if you'd like, make a PR).

Thanks

**Comment by xgfd** [comment]
ok I'll make a PR :)
BTW very good work you've done

**Comment by agmoyano** [comment]
Merged PR, thanks!
