### ISSUE TITLE
npm installs older version

### ISSUE THREAD

**Issue by steverc** [agmoyano/OpenIDConnect#27]
Hi,
I'm installing your module using npm dependency; I added:
"openid-connect": "*"
to my package.json.

Problem is that it installs commit fc3ee33e285d5006df2563a82bf84454fc6773d4, and not the latest one, so I have issues with user info endpoint.

I changed my dependency to 
"openid-connect": "git://github.com/agmoyano/OpenIDConnect"
and it's working, but could you fix it so it works also the other way?

Thanks

**Comment by agmoyano** [comment]
ok, npm should install last version now (1.2.4)

Thanks for pointing this out.
