### ISSUE TITLE
Timeout crash

### ISSUE THREAD

**Issue by steverc** [agmoyano/OpenIDConnect#28]
After 1 hour the tokens expires; the timeout crashes the server.
It looks like the problem is in index.js at line 954:
https://github.com/agmoyano/OpenIDConnect/blob/master/index.js#L954

Probably auth.access and/or auth.refresh do not exist, and that's the reason of the crash...

**Comment by agmoyano** [comment]
Hi, I'll check into it. Would you like to PR?

Thanks

**Comment by steverc** [comment]
Hi, I added a PR that avoids crash, but I'm not sure about functionality...
Thanks!
