### ISSUE TITLE
Typo in error messaging

### ISSUE THREAD

**Issue by dash-** [agmoyano/OpenIDConnect#35]
Minor issue: when more than one required scope is not granted, the error message includes a typo:

> "Required scopes openid and email **where** not granted."

Should be:

> "Required scopes openid and email **were** not granted."

Corresponds to line 1051 of master:

```
self.errorHandle(res, null, 'invalid_scope', 'Required scopes '+errors.join(', ')+' and '+last+' where not granted.');
```

**Comment by agmoyano** [comment]
@dash- Thanks for PR.

Cheers
